apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabitmqnovexam
spec:
  selector:
    matchLabels:
      app: rabitmqnovexam
  template:
    metadata:
      labels:
        app: rabitmqnovexam
    spec:
      containers:
      - name: rabitmqnovexam
        image: rabbitmq:3.9-management

---
apiVersion: v1
kind: Service
metadata:
  name: rabitmqnovexam
spec:
  type: NodePort
  selector:
    app: rabitmqnovexam
  ports:
  - port: 80
    targetPort: 15672
    nodePort: 32000
    name: "management"
  - port: 5672
    targetPort: 5672
    nodePort: 31672
    name: "connection"